pragma Singleton
import QtQuick

QtObject {
    readonly property string home: "file:///tmp/mock-home"
    readonly property string config: "file:///tmp/mock-config"
    readonly property string state: "file:///tmp/mock-state"
    readonly property string cache: "file:///tmp/mock-cache"
    readonly property string genericCache: "file:///tmp/mock-cache"
    readonly property string documents: "file:///tmp/mock-documents"
    readonly property string downloads: "file:///tmp/mock-downloads"
    readonly property string pictures: "file:///tmp/mock-pictures"
    readonly property string music: "file:///tmp/mock-music"
    readonly property string videos: "file:///tmp/mock-videos"

    property string assetsPath: "/tmp/mock-assets"
    property string scriptPath: "/tmp/mock-scripts"
    property string favicons: "/tmp/mock-cache/media/favicons"
    property string coverArt: "/tmp/mock-cache/media/coverart"
    property string tempImages: "/tmp/mock-cache/media/images"
    property string booruPreviews: "/tmp/mock-cache/media/boorus"
    property string booruDownloads: "/tmp/mock-pictures/homework"
    property string booruDownloadsNsfw: "/tmp/mock-pictures/homework/🌶️"
    property string latexOutput: "/tmp/mock-cache/media/latex"
    property string shellConfig: "/tmp/mock-config/illogical-impulse"
    property string shellConfigName: "config.json"
    property string shellConfigPath: "/tmp/mock-config/illogical-impulse/config.json"
    property string todoPath: "/tmp/mock-state/user/todo.json"
    property string notesPath: "/tmp/mock-state/user/notes.txt"
    property string conflictCachePath: "/tmp/mock-cache/conflict-killer"
    property string notificationsPath: "/tmp/mock-cache/notifications/notifications.json"
    property string generatedMaterialThemePath: "/tmp/mock-state/user/generated/colors.json"
    property string generatedWallpaperCategoryPath: "/tmp/mock-state/user/generated/wallpaper/category.txt"
    property string cliphistDecode: "/tmp/mock-cache/cliphist"
    property string screenshotTemp: "/tmp/mock-cache/screenshot"
    property string wallpaperSwitchScriptPath: "/tmp/mock-scripts/colors/switchwall.sh"
    property string defaultAiPrompts: "/tmp/mock-assets/defaults/ai/prompts"
    property string userAiPrompts: "/tmp/mock-config/illogical-impulse/ai/prompts"
    property string userActions: "/tmp/mock-config/illogical-impulse/actions"
    property string aiChats: "/tmp/mock-state/user/ai/chats"
    property string aiTranslationScriptPath: "/tmp/mock-scripts/ai/gemini-translate.sh"
    property string recordScriptPath: "/tmp/mock-scripts/videos/record.sh"
    property string userAvatarPathAccountsService: "/tmp/mock-avatar-accounts"
    property string userAvatarPathRicersAndWeirdSystems: "/tmp/mock-avatar-face"
    property string userAvatarPathRicersAndWeirdSystems2: "/tmp/mock-avatar-face-icon"
    property string userPresetsPath: "/tmp/mock-config/illogical-impulse/presets"
    property string presetsScriptPath: "/tmp/mock-scripts/presets.sh"
}
